### ISSUE TITLE
Source Codes

### ISSUE THREAD

**Issue by ActaVista** [gt0day/DarkWeb#1]
Any links for source codes for software developers?

**Comment by sindypaola32** [comment]
RnJvbTogPFNhdmVkIGJ5IEJsaW5rPg0KU25hcHNob3QtQ29udGVudC1Mb2NhdGlvbjogaHR0cHM6 Ly9oYWNraW5nLXRvci5jb20vZGF0b3MvP21kNWJhY2t1cD1HSUxzTk1JNEpFSUVPTEQ4OTc0MjQ4 S0kyRDI4OGVJOExITUxKNnM3SzVFNEZISzI5RUFCNjJQS0NCSTdGUTk4czg4Mjk4RDlKNzJFODk0 Sk9ONUtWMjVONjRPWjZIZTdJNUZHODY1OTRQczRNN1l3TzJFTjJCQzk3Qk5IS0xIRU8yME1ZWDM2 NU04RzhHSzdDSEs2SVFFN0JKNlBENzZFNjJRMk1ERUVLRU03NU43NTNNRDhGMzhHNzhMc1c4NzdC TTVLczVEMjYzMmVLNE44ODY3M0o1QUpOUDBRSEM5OEM3Qjg0RXMyQjcyQTVHTzhaZEIyRlBMODIy TzM4NTVMQTRBN0k0NjQ5RDg0ZTNBQUI0UDJJUUk0NzVzR0tBNjhNTEw4QTc5NEM3NGRzRkZFcjJz SDlGRVBGOTdQZUQyOEcwRUg4NVhFOTRDT0g0M0NHOUI3SzVlRmUyOE40TU84Tk44NTQySTgyZTVM OUE3SEgwSjg3QTU5NDI4czdJTDg5OENPc0w0NTY5T1BKOTBPUU9kWU42NjkyNjQ3QnNMR0JKSDg2

**Comment by ActaVista** [comment]
What's this sindy? Doesn't look like a link.
